services:
  web:
    build: .

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env.docker

    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine

    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: .
    command: celery -A backend.web.celery_app.celery worker --loglevel=info
    volumes:
      - .:/app

    depends_on:
      redis:
        condition: service_started

    env_file:
      - .env.docker

  celery_beat:
    build:
      context: .
    command: celery -A backend.web.celery_app.celery beat --loglevel=info
    volumes:
      - .:/app

    depends_on:
      redis:
        condition: service_started

    env_file:
      - .env.docker

volumes:
  postgres_data:
  redis_data:
