services:
  web:
    build: .

    ports:
      - '8000:8000'

    volumes:
      - ./data:/app/data

    env_file:
      - .env.docker

    depends_on:
      - db

  db:
    image: postgres:17

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - '5432:5432'

    env_file:
      - .env.db

volumes:
  postgres_data:
