services:
  web:
    build: .

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env.docker

    depends_on:
      - db

  db:
    image: postgres:17

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - "5432:5432"

    env_file:
      - .env.db

  redis:
    image: redis:7-alpine

    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: .
    command: celery -A backend.web.celery_app.celery worker --loglevel=info
    volumes:
      - .:/app

    depends_on:
      - db
      - redis

    env_file:
      - .env.docker

  celery_beat:
    build:
      context: .
    command: celery -A backend.web.celery_app.celery beat --loglevel=info
    volumes:
      - .:/app

    depends_on:
      - redis

    env_file:
      - .env.docker

volumes:
  postgres_data:
  redis_data:
