"""Add owner_firebase_uid to Note model

Revision ID: 42b98d3981a7
Revises: 1e1f909c9059
Create Date: 2025-09-21 10:37:53.534495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b98d3981a7'
down_revision: Union[str, Sequence[str], None] = '1e1f909c9059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('owner_firebase_uid', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_notes_owner_firebase_uid'), 'notes', ['owner_firebase_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_owner_firebase_uid'), table_name='notes')
    op.drop_column('notes', 'owner_firebase_uid')
    # ### end Alembic commands ###
