// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCod-SvmzTm24iOyzvCC6nXMDuD3Ce7vIo',
    appId: '1:364333285257:web:6adf46d34ee6203521eb58',
    messagingSenderId: '364333285257',
    projectId: 'living-diary-32de8',
    authDomain: 'living-diary-32de8.firebaseapp.com',
    storageBucket: 'living-diary-32de8.firebasestorage.app',
    measurementId: 'G-NTSFLN17JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyaai0rL3xyEQTF2jlSZCHr0pLPoAid0M',
    appId: '1:364333285257:android:33c9da157cb0c05221eb58',
    messagingSenderId: '364333285257',
    projectId: 'living-diary-32de8',
    storageBucket: 'living-diary-32de8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV3TV2D6dujFWDfsMuYK-bR_TT-cht3FY',
    appId: '1:364333285257:ios:803e9ab14ff939ee21eb58',
    messagingSenderId: '364333285257',
    projectId: 'living-diary-32de8',
    storageBucket: 'living-diary-32de8.firebasestorage.app',
    androidClientId: '364333285257-8ou7vijep0qm10809pntc7thpjl7j19o.apps.googleusercontent.com',
    iosClientId: '364333285257-4c8uk1ln0fvk84u7k7f953rmut4oh8tn.apps.googleusercontent.com',
    iosBundleId: 'com.volkswagen.livingDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV3TV2D6dujFWDfsMuYK-bR_TT-cht3FY',
    appId: '1:364333285257:ios:803e9ab14ff939ee21eb58',
    messagingSenderId: '364333285257',
    projectId: 'living-diary-32de8',
    storageBucket: 'living-diary-32de8.firebasestorage.app',
    androidClientId: '364333285257-8ou7vijep0qm10809pntc7thpjl7j19o.apps.googleusercontent.com',
    iosClientId: '364333285257-4c8uk1ln0fvk84u7k7f953rmut4oh8tn.apps.googleusercontent.com',
    iosBundleId: 'com.volkswagen.livingDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCod-SvmzTm24iOyzvCC6nXMDuD3Ce7vIo',
    appId: '1:364333285257:web:f63ccb905672563121eb58',
    messagingSenderId: '364333285257',
    projectId: 'living-diary-32de8',
    authDomain: 'living-diary-32de8.firebaseapp.com',
    storageBucket: 'living-diary-32de8.firebasestorage.app',
    measurementId: 'G-SQSQEJC6JH',
  );
}
