"""Refactoring for correct relationships

Revision ID: 5334c39e3f90
Revises: 152866b0b9d5
Create Date: 2025-10-09 11:24:50.361828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5334c39e3f90'
down_revision: Union[str, Sequence[str], None] = '152866b0b9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'chat_id')
    # ### end Alembic commands ###
