"""Add column chat_id

Revision ID: f2c8b85db1da
Revises: 5334c39e3f90
Create Date: 2025-10-13 14:29:34.825496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c8b85db1da'
down_revision: Union[str, Sequence[str], None] = '5334c39e3f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'chat_id')
    op.add_column('users', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id')
    op.add_column('notes', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
